"""
build.py - Aplana los scripts de componentes a la raiz para Plant 3D.

Plant 3D (varmain) solo registra scripts Python colocados directamente en
CustomScripts/. Para mantener el repositorio ordenado por familias, cada
componente se crea en su subcarpeta y este script los copia a la raiz.

Uso:
    python build.py              # aplanar (borra outputs antiguos y regenera)
    python build.py --check      # solo validar (para CI), no escribe nada
    python build.py --dry-run    # mostrar que haria sin escribir

Los archivos generados llevan un marcador y no deben editarse a mano:
si modificas un componente, edita la version en su subcarpeta y vuelve a
ejecutar este script.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent

FAMILIES_DIR = ROOT / "src" / "families"
LIB_DIR = ROOT / "src" / "lib"

SOURCE_DIRS = [d.name for d in FAMILIES_DIR.iterdir() if d.is_dir()] if FAMILIES_DIR.exists() else []

# Archivos de la raiz que nunca se consideran output generado.
PROTECTED = {
    "__init__.py",
    "build.py",
    "build_catalog.py",
    "Swagelok_Catalog.pcat",
    "README.md",
    "AGENTS.md",
    ".gitignore",
    "requirements.txt",
    "pyproject.toml",
}

GENERATED_PREFIX = "# AUTOGENERATED by build.py"
GENERATED_MARKER = GENERATED_PREFIX + " -- do not edit (source: {src})"
_HEADER_RE = re.compile(r"^# AUTOGENERATED by build\.py.*$", re.M)

_ACTIVATE_RE = re.compile(r"@activate\s*\(")
# Funcion registrable de un script Plant 3D, p.ej. "def SIMPLE_TEE("
_FUNC_RE = re.compile(r"def\s+([A-Z][A-Z0-9_]*)\s*\(")
_COMMENT_RE = re.compile(r"^\s*#", re.M)
_STRING_RE = re.compile(r"^\s*(?:'''|\"\"\")", re.M)

GITIGNORE_START = "# >>> generated by build.py"
GITIGNORE_END = "# <<< generated by build.py"


class BuildError(Exception):
    """Error estructural en el repositorio de componentes."""


def strip_comments(text):
    """Elimina comentarios y docstrings para que el regex de def no falle."""
    lines = []
    for line in text.splitlines():
        if _STRING_RE.match(line) or _COMMENT_RE.match(line):
            continue
        # Quita comentarios al final de linea (fuera de cadenas, aproximado).
        if "#" in line and not (line.count('"') % 2 or line.count("'") % 2):
            line = line.split("#", 1)[0]
        lines.append(line)
    return "\n".join(lines)


def find_registration_name(path):
    """Devuelve el nombre registrable (funcion con @activate) del script."""
    text = strip_comments(path.read_text(encoding="utf-8"))
    activate = _ACTIVATE_RE.search(text)
    if not activate:
        raise ValueError(f"No se encontro @activate en {path}")
    match = _FUNC_RE.search(text, activate.start())
    if not match:
        raise ValueError(
            f"No se encontro 'def <NOMBRE>(' despues de @activate en {path}"
        )
    return match.group(1)


def iter_components(root=ROOT):
    """Devuelve {nombre_registrable: Path} para cada componente fuente."""
    components = {}
    families_dir = root / "src" / "families"
    if not families_dir.is_dir():
        return components
    for path in sorted(families_dir.rglob("*.py")):
        if path.name in ("__init__.py",) or path.name.startswith("_"):
            continue
        if GENERATED_PREFIX in path.read_text(encoding="utf-8", errors="ignore"):
            continue
        name = find_registration_name(path)
        if name in components:
            raise BuildError(
                f"Nombre registrable duplicado: {name}\n"
                f"  -> {components[name]}\n"
                f"  -> {path}\n"
                "Cada componente debe tener un nombre de funcion unico."
            )
        components[name] = path
    if not components:
        raise BuildError("No se encontraron componentes en las subcarpetas.")
    return components


def output_path(root, src_path):
    families_dir = root / "src" / "families"
    rel = src_path.relative_to(families_dir)
    family = rel.parts[0]
    stem = src_path.stem
    return root / f"{family}.{stem}.py"


def list_generated_in_root(root=ROOT):
    """Devuelve los .py de la raiz que llevan el marcador de generado."""
    generated = []
    for path in sorted(root.glob("*.py")):
        if path.name in PROTECTED or path.name == "__init__.py":
            continue
        if _HEADER_RE.search(path.read_text(encoding="utf-8", errors="ignore")):
            generated.append(path)
    return generated


def expected_content(root, src_path):
    header = GENERATED_MARKER.format(src=src_path.relative_to(root).as_posix())
    body = src_path.read_text(encoding="utf-8").rstrip()
    return f"{header}\n{body}\n"


def sync_gitignore(root=ROOT, generated_names=()):
    """Mantiene el bloque de .gitignore con los outputs generados."""
    gi_path = root / ".gitignore"
    block = [GITIGNORE_START, *[f"/{name}" for name in sorted(generated_names)],
             GITIGNORE_END]
    text = gi_path.read_text(encoding="utf-8") if gi_path.exists() else ""
    lines = text.splitlines()
    try:
        i_start = next(i for i, l in enumerate(lines) if l == GITIGNORE_START)
        i_end = next(i for i, l in enumerate(lines) if l == GITIGNORE_END)
        lines[i_start : i_end + 1] = block
    except StopIteration:
        if lines:
            lines.append("")
        lines.extend(block)
    # Preserva el fin de linea del archivo original (Windows usa CRLF).
    newline = "\r\n" if "\r\n" in text else "\n"
    gi_path.write_text(newline.join(lines) + newline, encoding="utf-8")


def get_lib_files(root=ROOT):
    """Devuelve la lista de archivos lib en src/lib que deben ser copiados."""
    lib_dir = root / "src" / "lib"
    if not lib_dir.is_dir():
        return []
    return [p for p in lib_dir.glob("*.py") if p.name != "__init__.py"]


def _collisions(output_names):
    """Archivos cuyo output colisiona con un archivo protegido."""
    return [name for name in output_names if name in PROTECTED]


def collect_errors(root=ROOT):
    """Devuelve la lista de errores de sincronizacion raiz <-> subcarpetas."""
    components = iter_components(root)
    lib_files = get_lib_files(root)
    
    expected_outputs = {}
    for name, src in components.items():
        expected_outputs[output_path(root, src).name] = expected_content(root, src)
    
    for lib_src in lib_files:
        expected_outputs[lib_src.name] = expected_content(root, lib_src)
        
    output_names = set(expected_outputs.keys())

    errors = []
    for out_name, content in expected_outputs.items():
        out = root / out_name
        if not out.exists():
            errors.append(f"Falta output aplanado: {out.name} (ejecuta python build.py)")
        elif out.read_text(encoding="utf-8") != content:
            errors.append(f"Output desactualizado: {out.name} (ejecuta python build.py)")

    stale = [p for p in list_generated_in_root(root) if p.name not in output_names]
    if stale:
        names = ", ".join(p.name for p in stale)
        errors.append(f"Outputs obsoletos en raiz: {names} (ejecuta python build.py)")

    for name in _collisions(output_names):
        errors.append(
            f"Un archivo generaria '{name}', un archivo protegido. Renombralo."
        )
    return errors


def flatten(root=ROOT):
    """Aplana los componentes de las subcarpetas a la raiz."""
    components = iter_components(root)
    lib_files = get_lib_files(root)

    expected_outputs = {}
    for name, src in components.items():
        expected_outputs[output_path(root, src).name] = (src, expected_content(root, src))
    
    for lib_src in lib_files:
        expected_outputs[lib_src.name] = (lib_src, expected_content(root, lib_src))
        
    output_names = list(expected_outputs.keys())

    for name in _collisions(output_names):
        raise BuildError(
            f"Un archivo generaria '{name}', un archivo protegido. Renombralo."
        )

    for p in list_generated_in_root(root):
        if p.name not in output_names:
            p.unlink()
            print(f"Eliminado: {p.name}")

    for out_name, (src, content) in expected_outputs.items():
        out = root / out_name
        out.write_text(content, encoding="utf-8")
        print(f"Aplanado: {src.relative_to(root)} -> {out.name}")

    sync_gitignore(root, output_names)
    return components


def main():
    args = sys.argv[1:]
    check_only = "--check" in args
    dry_run = "--dry-run" in args
    if check_only and dry_run:
        raise SystemExit("Usa solo uno de --check o --dry-run.")

    try:
        if check_only:
            errors = collect_errors(ROOT)
            if errors:
                raise SystemExit("\n".join("[CHECK FAIL] " + e for e in errors))
            components = iter_components(ROOT)
            lib_files = get_lib_files(ROOT)
            count = len(components) + len(lib_files)
            print(f"[OK] {count} archivos validados, raiz sincronizada.")
            return

        components = iter_components(ROOT)
        lib_files = get_lib_files(ROOT)
        print("Archivos encontrados:")
        for name in sorted(components):
            print(f"  {name:<20} -> {components[name].relative_to(ROOT)}")
        for lib_src in lib_files:
            print(f"  [lib] {lib_src.name:<16} -> {lib_src.relative_to(ROOT)}")

        output_names = {output_path(ROOT, src).name for src in components.values()}
        output_names.update(lib_src.name for lib_src in lib_files)
        
        stale = [p for p in list_generated_in_root(ROOT) if p.name not in output_names]
        if stale:
            print("\nOutputs obsoletos que se eliminaran:")
            for p in stale:
                print(f"  - {p.name}")

        if dry_run:
            print("\n[dry-run] No se escribieron archivos.")
            return

        flatten(ROOT)
        print("\nListo. Ejecuta PLANTREGISTERCUSTOMSCRIPTS en AutoCAD Plant 3D.")
    except BuildError as exc:
        raise SystemExit(f"[ERROR] {exc}")


if __name__ == "__main__":
    main()
